### ISSUE TITLE
现在删除这个储存库

### ISSUE THREAD

**Issue by NotFlyLoongQaQ** [fuck-23/fuck-23.github.io#1]
现在删除这个储存库，否则我有权根据《中华人民共和国民法典》对您进行起诉，您已经对我的名誉权造成侵害。

**Comment by NotFlyLoongQaQ** [comment]
根据刑法第246条的规定，以暴力或者其他方法公然侮辱他人的应当立案。您的储存库以及组织名称为“Fuck-23"，这对我的人格进行了侮辱以及对我的名誉权进行侵害，您应当公开道歉，或者 see u 法院。

**Comment by xjzh123** [comment]
抱歉，您没有证明您就是存储库标题所指的23

**Comment by NotFlyLoongQaQ** [comment]
我有证据。我可以在 minecraftbox.link 建立验证文件。

**Comment by NotFlyLoongQaQ** [comment]
另：任何对该 issues 的包括但不限于修改，关闭，合并等类操作都视为对我言论自由权利的侵犯。

**Comment by yu22c0w0** [comment]
抱歉，这是我家老鼠踩到屏幕了

**Comment by huolongguo1O** [comment]
我们有关闭issue的自由，但你没有诽谤的自由

**Comment by NotFlyLoongQaQ** [comment]
抱歉，对于该储存库，应该由它的账号的注册者负责。

**Comment by yu22c0w0** [comment]
> 抱歉，对于该储存库，应该由它的账号的注册者负责。

但这是我家老鼠写的

**Comment by NotFlyLoongQaQ** [comment]
我并没有诽谤，反而是你对我进行了诽谤。
- 我没有虚构事实。
- 我没有侵害你们的名誉。
但是您对我的名誉造成了损失。

**Comment by NotFlyLoongQaQ** [comment]
即使是您的老鼠写的，您也要为您老鼠在您账号上的行为负责，因为您是这个账号的建立者，而且您没有说明您是老鼠。

**Comment by yu22c0w0** [comment]
> 即使是您的老鼠写的，您也要为您老鼠在您账号上的行为负责，因为您是这个账号的建立者，而且您没有说明您是老鼠。

```
nHNvSB 23_s_mouse
如果每一次输入都是最理想的 我就是老鼠
```

**Comment by huolongguo1O** [comment]
> 我并没有诽谤，反而是你对我进行了诽谤。
> 
> * 我没有虚构事实。
> * 我没有侵害你们的名誉。
>   但是您对我的名誉造成了损失。

所有内容属实，没有诽谤

**Comment by NotFlyLoongQaQ** [comment]
您需要影像资料对您的老鼠创建了该储存库进行证明。

**Comment by NotFlyLoongQaQ** [comment]
> > 我并没有诽谤，反而是你对我进行了诽谤。
> > 
> > * 我没有虚构事实。
> > * 我没有侵害你们的名誉。
> >   但是您对我的名誉造成了损失。
> 
> 所有内容属实，没有诽谤

您有什么证据证明是我干的？

**Comment by NotFlyLoongQaQ** [comment]
> 您需要影像资料对您的老鼠创建了该储存库进行证明。

此外，您没有明白我的意思，您应当对您的账号进行负责，不管是谁在操作

**Comment by NotFlyLoongQaQ** [comment]
即使是您的老鼠创建了该储存库您也有义务对该储存库进行删除。

**Comment by yu22c0w0** [comment]
> > 您需要影像资料对您的老鼠创建了该储存库进行证明。
> 
> 此外，您没有明白我的意思，您应当对您的账号进行负责，不管是谁在操作

```
0/JM7u Radium_lblue__
你有证据你是老鼠吗

0/JM7u Radium_lblue__ 你有证据是老鼠打的吗

nHNvSB 23 刚才有老鼠在我键盘上一直跳
```

**Comment by MaggieLOL** [comment]
@yu22c0w0 suggest: add label "invaild" and close as "not planned"

**Comment by xjzh123** [comment]
> 我有证据。我可以在 minecraftbox.link 建立验证文件。

你是minecraftbox.link的拥有者，这是否可以说明你就是标题中所述的23？

**Comment by MaggieLOL** [comment]
我去，我发现github issue是个好聊天室

**Comment by MaggieLOL** [comment]
甚至实时&邮箱通知

**Comment by huolongguo1O** [comment]
1.DDoS 您在lounge中确实扬言过DDoS，且发过DDoS网站的代码
2.召唤网警 您多次举报hc系列聊天室，请求望京的帮忙
3.所有历史记录都为事实

**Comment by MaggieLOL** [comment]
你们发个消息我手机就震一下

**Comment by yu22c0w0** [comment]
想问一下，半夜12点的HTTP POST flood的你干的吗

**Comment by NotFlyLoongQaQ** [comment]
不是我，可能是ice或者是我其他盟友亦或者是无目的攻击者。

> 不开CDN发争议性内容活该。

**Comment by NotFlyLoongQaQ** [comment]
以及如果20G不是瞬时流量的话并不算高，我被200Gbps过。

**Comment by yu22c0w0** [comment]
我已经确定不是了

**Comment by zzChumo** [comment]
破案了，23是芙卡洛斯假扮的
